<#
Module manifest for the 'cMsmq' DSC resource module.
Generated by Serge Nikalaichyk.
#>

@{
    ModuleVersion = '1.0.4'
    GUID = 'a9af3532-64f2-43b4-81f1-a5324f553dd1'
    Author = 'Serge Nikalaichyk'
    Copyright = '(c) 2016 Serge Nikalaichyk. All rights reserved.'
    Description = 'The cMsmq module contains DSC resources for managing MSMQ queues. Supports Windows Server 2008 R2 and later.'
    PowerShellVersion = '4.0'
    CLRVersion = '4.0'
    FunctionsToExport = '*'
    CmdletsToExport = '*'
    VariablesToExport = '*'
    AliasesToExport = '*'
    PrivateData = @{
        PSData = @{
            Tags = @('AccessControl', 'DesiredStateConfiguration', 'DSC', 'MessageQueue', 'MessageQueueAccessRights', 'MSMQ', 'PSModule', 'Queue')
            LicenseUri = 'https://github.com/SNikalaichyk/cMsmq/blob/master/LICENSE'
            ProjectUri = 'https://github.com/SNikalaichyk/cMsmq'
        }
    }
}
