[ClassVersion("1.0.0.0"), FriendlyName("cMsmqQueuePermissionEntry")]
class cMsmqQueuePermissionEntry : OMI_BaseResource
{
    [Write, Description("Indicates whether the permission entry exists."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;
    [Key, Description("Indicates the name of the queue.")] String Name;
    [Key, Description("Indicates the identity of the principal.")] String Principal;
    [Write, Description("Indicates the access rights to be granted to the principal.")] String AccessRights[];
};
