[ClassVersion("1.0.0.0"), FriendlyName("cMsmqQueue")]
class cMsmqQueue : OMI_BaseResource
{
    [Write, Description("Indicates whether the queue exists."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;
    [Key, Description("Indicates the name of the queue.")] String Name;
    [Write, Description("Indicates whether the queue is transactional.")] Boolean Transactional;
    [Write, Description("Indicates whether the queue accepts only authenticated messages.")] Boolean Authenticate;
    [Write, Description("Indicates whether received messages are copied to the journal queue.")] Boolean Journaling;
    [Write, Description("Indicates the maximum size of the journal queue in KB.")] UInt32 JournalQuota;
    [Write, Description("Indicates the description of the queue.")] String Label;
    [Write, Description("Indicates the privacy level associated with the queue."), ValueMap{"None","Optional","Body"}, Values{"None","Optional","Body"}] String PrivacyLevel;
    [Write, Description("Indicates the maximum size of the queue in KB.")] UInt32 QueueQuota;
};
